### ISSUE TITLE
omnetics-adapter-64

### ISSUE THREAD

**Issue by ChangQing-SH** [jonnew/ONIX#26]
Hi, 
this adapter is used with omnetics-EIB, any adapter works with your Hirose-EIB?    Hirose-64 to Omnetics 32*2?

Thanks,

**Comment by jonnew** [comment]
Hi,

I don't understand your question. Can you be more descriptive please?

**Comment by ChangQing-SH** [comment]
your omnetics-adapter is for the old Omnetics-EIB （Omnetics to Hirose), but I want to use your Hirose-64 EIB with my Intan headstage,  so I need one Hirose to Omnetics

**Comment by jonnew** [comment]
OK, if I'm understanding you, then that's exactly what omnetics-adapter-64 does. It allows you to use the eib-64 (https://open-ephys.org/drive-implant/64-channel-eib-lyfw2) on your drive implant and then convert that connection to a standard, 64-channel intan headstage (https://intantech.com/RHD_headstages.html?tabSelect=RHD64ch&yPos=0).

**Comment by jonnew** [comment]
I see. We don't offer that because its regression in functionality. The ONIX project provides advanced serialization capabilities that are fundamentally incompatible with older, SPI based headstages.

If you just want to use the Hiroise EIBs with SPI based headstages, consider purchasing our low-profile SPI headstage (https://open-ephys.org/acquisition-system/low-profile-spi-headstage-64ch).
